package org.example.model

import com.fasterxml.jackson.annotation.JsonInclude

// Import all generated models
import org.example.model.generated.*

/**
 * Meeple model for API responses (not generated by OpenAPI)
 */
data class Meeple(
    val playerId: String,
    val position: String,
    val featureId: String
)

/**
 * Game options model (not generated by OpenAPI)
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
data class GameOptions(
    val includeExpansions: List<String>? = null,
    val maxPlayers: Int? = null,
    val timerSeconds: Int? = null
)

/**
 * Feature score info model (not generated by OpenAPI)
 */
data class FeatureScoreInfo(
    val featureType: String,
    val completed: Boolean
)

// Create an ErrorResponse class since it's used in many places
data class ErrorResponse(
    val errorCode: String,
    val errorMessage: String
)

// Create a ScoreUpdate class for compatibility
data class ScoreUpdate(
    val playerId: String,
    val points: Int,
    val feature: FeatureScoreInfo
)